# Generated by Django 4.1.4 on 2023-05-26 11:33

import admintion.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Davlat nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('duration_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'kun'), (2, 'oy'), (3, 'yil')], null=True)),
                ('lesson_duration', models.CharField(max_length=50)),
                ('lesson_duration_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'daqiqa'), (2, 'soat')], null=True)),
                ('price', models.PositiveIntegerField()),
                ('price_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, "so'm"), (2, 'rubl'), (3, 'dollar')], null=True)),
                ('comment', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Viloyat nomi')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.countries', verbose_name='Davlat')),
            ],
        ),
        migrations.CreateModel(
            name='EduCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="O'quv markazi")),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manzil')),
                ('max_groups', models.PositiveIntegerField(default=0, verbose_name="Maksimal guruh sig'imi")),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('max_students', models.PositiveIntegerField(default=0, verbose_name="Maksimal o'quvchilar sig'imi")),
                ('teacher_can_see_payments', models.BooleanField(default=False, verbose_name="O'qituvchilar talaba to'lovlarini ko'rishi mumkin")),
                ('teacher_can_sign_contracts', models.BooleanField(default=False, verbose_name="O'quvchilar bilan shartnoma imzolash")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='educenters/logos')),
                ('oferta', models.FileField(blank=True, null=True, upload_to='educenters/')),
                ('s_contract', models.FileField(blank=True, null=True, upload_to='educenters/')),
                ('t_contract', models.FileField(blank=True, null=True, upload_to='educenters/')),
                ('j_contract', models.FileField(blank=True, null=True, upload_to='educenters/')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.countries')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.districts')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiallar', to='admintion.educenters')),
            ],
        ),
        migrations.CreateModel(
            name='EduFormats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ta'lim formati")),
            ],
        ),
        migrations.CreateModel(
            name='FormLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('telegram', models.CharField(max_length=100, null=True, verbose_name='Telegramdagi nomeri')),
                ('p_phone', models.CharField(max_length=100, null=True)),
                ('passport', models.CharField(max_length=10, null=True, verbose_name='Passport seriya va raqami')),
                ('file', models.FileField(null=True, upload_to='leads', validators=[admintion.validators.validate_file_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('activity', models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Arxiv'), (3, "O'chirilgan")], default=1, verbose_name='Lidning statusi')),
                ('purpose', models.CharField(max_length=300, null=True, verbose_name="O'qishdan maqsadi")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.course')),
            ],
        ),
        migrations.CreateModel(
            name='FormUniversalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('key', models.CharField(max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('required', models.BooleanField(default=False, verbose_name='Talab qilinadimi?')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pay_type', models.PositiveSmallIntegerField(choices=[(1, 'Darsbay'), (2, 'Oylik'), (3, 'Yillik'), (4, 'Modulli')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'tayyorlanmoqda'), (2, 'ishga tayyor'), (3, 'ishga tushgan'), (4, "To'xtab turipti"), (5, 'Tugatdi'), (6, 'Arxivchi')])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('limit', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comments', models.TextField(blank=True, default='', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.course')),
            ],
            managers=[
                ('groups', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, verbose_name='Status nomi')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='Status rangi')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=10, null=True, verbose_name='Passport')),
                ('telegram', models.CharField(max_length=16, null=True, verbose_name='Telegram contact number')),
                ('status', models.BooleanField(default=True)),
                ('educenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('educenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters')),
            ],
            managers=[
                ('rooms', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SmsIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.PositiveIntegerField(default=100, verbose_name='Smslar soniga cheklov')),
                ('used', models.PositiveIntegerField(default=0, verbose_name='Foydalanilgan bonus smslar soni')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Sms Integratsiya qilingan email')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sms Integratsiya qilingan parol')),
                ('main', models.BooleanField(default=False, help_text="Agar bu firmaning(o'quv markazniki emas) ma'lumotlari bo'lsa, belgilang", verbose_name='Asosiymi?')),
            ],
            options={
                'verbose_name': 'Sms Integratsiya',
                'verbose_name_plural': 'Sms Integratsiya',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('educenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Muzlatilgan'), (3, 'Ketgan')], default=1)),
                ('comment', models.TextField()),
                ('balance', models.IntegerField(default=0, verbose_name="O'quvchining hisobidagi mablag'")),
                ('pay_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Darsbay'), (2, 'Oylik'), (3, 'Yillik'), (4, 'Modulli')], null=True)),
                ('educenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters')),
                ('groups', models.ManyToManyField(related_name='student', to='admintion.group')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.sources')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=150, verbose_name='Topshiriq turi')),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whom', models.CharField(max_length=25, verbose_name='Kim uchun?')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacer_type', models.BooleanField(default=False)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('educenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('teachers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='Deadline:')),
                ('comment', models.CharField(max_length=500, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Bajarildi'), (3, 'Kechikkan')], default=1, verbose_name='Statusi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('courses', models.ManyToManyField(blank=True, to='admintion.course')),
                ('educenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters')),
                ('groups', models.ManyToManyField(blank=True, to='admintion.group')),
                ('leads', models.ManyToManyField(blank=True, to='admintion.formlead')),
                ('parents', models.ManyToManyField(blank=True, to='admintion.parents')),
                ('responsibles', models.ManyToManyField(related_name='user_tasks', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, to='admintion.student')),
                ('task_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.tasktypes')),
                ('user_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.usertaskstatus')),
                ('whom', models.ManyToManyField(related_name='my_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_image', to='admintion.room')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Viloyat nomi')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.countries', verbose_name='Davlat')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.SmallIntegerField(choices=[(1, 'Naqd'), (2, 'Payme'), (3, 'Click'), (4, 'Apelsin'), (5, 'Visa Card')], default=1, verbose_name="To'lov turi")),
                ('comment', models.CharField(max_length=500, null=True, verbose_name='Izoh')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='admintion.student')),
            ],
            managers=[
                ('payments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='parents',
            name='students',
            field=models.ManyToManyField(to='admintion.student'),
        ),
        migrations.AddField(
            model_name='parents',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=5000, verbose_name='Xabar matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.PositiveSmallIntegerField(choices=[(1, 'Foydalanuvchiga'), (2, "O'qituvchilarga"), (3, "O'quvchilarga"), (4, 'Ota-onalarga'), (5, 'Adminlarga'), (6, 'Managerlarga'), (7, "O'quvchilarga"), (8, 'Guruhga'), (9, 'Kursga'), (10, 'Lidlarga')], default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_messages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Forma nomi')),
                ('title', models.CharField(max_length=150, verbose_name='Forma sarlavhasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='forms')),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('russian', models.BooleanField(default=False)),
                ('english', models.BooleanField(default=False)),
                ('seen', models.PositiveIntegerField(default=0)),
                ('qrcode', models.ImageField(null=True, upload_to='formleads')),
                ('courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admintion.course')),
                ('educenters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admintion.educenters')),
                ('sources', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admintion.sources')),
            ],
            managers=[
                ('lead_forms', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LeadDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Demo dars sanaga belgilandi:')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.group')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo', to='admintion.formlead')),
            ],
        ),
        migrations.CreateModel(
            name='GroupStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Aktiv'), (2, 'Muzlatilgan'), (3, 'Ketgan')], default=1)),
                ('attend_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='admintion.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ggroups', to='admintion.student')),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupsDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(choices=[(1, 'Du'), (2, 'Se'), (3, 'Chor'), (4, 'Pay'), (5, 'Ju'), (6, 'Sha'), (7, 'Yak')])),
                ('educenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='days',
            field=models.ManyToManyField(to='admintion.groupsdays'),
        ),
        migrations.AddField(
            model_name='group',
            name='educenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters'),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.room'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teacher', to='admintion.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='admintion.teacher'),
        ),
        migrations.AddField(
            model_name='formlead',
            name='days',
            field=models.ManyToManyField(blank=True, to='admintion.groupsdays'),
        ),
        migrations.AddField(
            model_name='formlead',
            name='educenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters'),
        ),
        migrations.AddField(
            model_name='formlead',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.parents'),
        ),
        migrations.AddField(
            model_name='formlead',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.sources'),
        ),
        migrations.AddField(
            model_name='formlead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.leadstatus'),
        ),
        migrations.AddField(
            model_name='formlead',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formlead',
            name='via_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.leadforms'),
        ),
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('key', models.CharField(max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('required', models.BooleanField(default=False, verbose_name='Talab qilinadimi?')),
                ('leadform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.leadforms')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.PositiveSmallIntegerField(choices=[(1, 'online'), (2, 'offline')], default=1)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'tur 1'), (2, 'tur 2')], default=1)),
                ('title', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('file', models.FileField(upload_to='educenters/')),
                ('educenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters')),
            ],
        ),
        migrations.AddField(
            model_name='educenters',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.regions'),
        ),
        migrations.AddField(
            model_name='districts',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.regions', verbose_name='Viloyati'),
        ),
        migrations.AddField(
            model_name='course',
            name='educenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.PositiveSmallIntegerField(choices=[(1, 'Telegram'), (2, 'Instagram'), (3, 'Facebook'), (4, 'Twitter'), (5, 'Youtube'), (6, 'Telefon'), (7, 'Havola')], verbose_name='Aloqa turi')),
                ('value', models.CharField(max_length=150)),
                ('leadform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.leadforms')),
            ],
        ),
        migrations.CreateModel(
            name='Attendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Kechikdi'), (2, 'Keldi'), (3, 'Sababsiz'), (4, 'Sababli')], null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reasen', models.SmallIntegerField(blank=True, choices=[(1, "Qattiq kasal bo'lgan"), (2, 'Talaba viloyatga ketgan'), (3, '2-darsga kelmadi'), (4, '3-darsga kelmadi')], null=True)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendaces', to=settings.AUTH_USER_MODEL)),
                ('group_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to='admintion.groupstudents')),
                ('lead_demo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_attendance', to='admintion.leaddemo')),
            ],
        ),
    ]
