# Generated by Django 4.1.4 on 2023-05-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupstudents',
            unique_together={('student', 'group')},
        ),
    ]
