from django.urls import path
from django.views.generic import TemplateView
from admintion.views import employes,rooms,courses,teachers,groups,students,forms,leads,tasks,sms,reports, educenters, settings, dashboard
app_name = 'admintion'

urlpatterns = [
    path('employees/',employes.employees_view,name='employees'),
    path('employee/<int:id>/detail/',employes.employee_detail_view,name='employee-detail'),
    path('rooms/',rooms.rooms_view,name='rooms'),
    path('courses/',courses.courses_view,name='courses'),
    path('courses/<int:pk>/delete/', courses.course_delete_view, name='course-delete'),
    path('courses/<int:pk>/detail/', courses.course_detail_view, name='course-detail'),
    path('courses/<int:pk>/update/', courses.course_update_view, name='course-update'),
    path('teachers/',teachers.teachers_view,name='teachers'),
    path('teacher/<int:id>/detail/',teachers.teacher_detail_view,name='teacher-detail'),
    path('teacher/<int:id>/delete/',teachers.teacher_delete_view,name='teacher-delete'),
    path('teacher/<int:id>/update/',teachers.teacher_update_view,name='teacher-update'),
    path('groups/',groups.groups_view,name='groups'),
    path('group-list/',groups.group_list_view,name='group-list'),
    path('group/<int:id>/detail/',groups.group_detail_view,name='group-detail'),
    path('group/<int:id>/data/',groups.group_detail_data,name='group-data'),
    path('group/change/attendace/',groups.change_attendace_view,name='change-attendace'),
    path('group/change/lead-attendace/',groups.change_lead_attendace_view,name='change-lead-attendace'),
    path('group/change/get-attendace/',groups.get_attendace_view,name='get-attendace'),
    path('group/<int:id>/add/student/',groups.add_student_view,name='add-student'),
    path('students/',students.students_view,name='students'),
    path('student/<int:id>/detail/',students.student_detail_view,name='student-detail'),
    path('student/<int:id>/detail-data/',students.student_detail_data,name='student-detail-data'),
    path('student/<int:id>/',students.student_view,name='student'),
    path('student/<int:id>/delete/',students.student_delete_view,name='student-delete'),
    path('student/<int:id>/add-group/', students.student_add_group_view, name='add-student-to-group'),
    path('student/<int:id>/deactivate-in-group/', students.student_deactivate_view, name='deactivate-student-in-group'),
    path('student/<int:id>/remove-in-group/', students.student_remove_view, name='remove-student-in-group'),
    path('student/<int:id>/activate-in-group/', students.student_activate_view, name='activate-student-in-group'),
    path('forms/',forms.forms_view,name='forms'),
    path('forms/<int:pk>/',forms.form_update_view,name='form-update'),
    path('forms/<int:pk>/detail/',forms.form_detail_view,name='form-detail'),
    path('forms/<int:pk>/delete/',forms.form_delete_view,name='form-delete'),
    path('forms/uni-fields/',forms.universal_fields_view,name='universal-fields'),
    path('forms/<int:pk>/fields/', forms.form_fields_view, name='form_fields'),
    path('forms/<int:pk>/fields/delete/', forms.form_fields_delete_view, name='form_fields_delete'),
    path('forms/<int:pk>/contacts/', forms.contacts_view, name='form_contacts'),
    path('forms/<int:pk>/contacts/delete/', forms.contacts_delete_view, name='form_contacts_delete'),
    path('leads/',leads.leads_view,name='lead-list'),
    path('leads/create/', leads.lead_create_view, name='lead-create'),
    path('leads/<int:pk>/',leads.lead_detail_view, name='lead-detail'),
    path('leads/<int:pk>/update/',leads.lead_edit_view, name='lead-update'),
    path('leads/<int:pk>/add-group/', leads.addto_group, name='lead-add-to-group'),
    path('leads/<int:pk>/<str:action>/', leads.lead_activity_change, name='lead-activity-change'),
    path('leads/add-demo/', leads.add_demo, name='add-demo'),
    path('tasks/create/', tasks.add_task, name='add-task'),

    path('sms/check/', sms.check_sms_availability, name='check-sms-availability'),
    path('sms/send/lead/', sms.send_sms_to_lead, name='send_sms_to_lead'),
    path('sms/send/student/', sms.send_sms_to_students, name='send_sms_to_student'),
    path('sms/send/group/', sms.send_sms_to_group, name='send_sms_to_group'),
    path('sms/send/teacher/', sms.send_sms_to_teacher, name='send_sms_to_teacher'),
    path('sms/send/parent/', sms.send_sms_to_parent, name='send_sms_to_parent'),
        
    path('reports/', reports.reports_view, name='reports'),
    path('educenters/', educenters.educenters_view, name='edu-centers'),
    path('educenters/<int:pk>/delete/', educenters.educenter_delete_view, name='edu-centers-delete'),
    path('educenters/<int:pk>/data/', educenters.educenter_detail, name='edu-centers-detail-data'),
    path('educenters/<int:pk>/update/', educenters.educenter_update_view, name='edu-centers-update'),
    path('connected_regs/', educenters.connected_regs, name='connected_regions'),
    path('settings/', settings.settings_view, name='settings'),

    path('', dashboard.dashboard, name='dashboard'),
    path('teacher/pay/', dashboard.teacher_pay, name='teacher_pay'),

    path('reports/finance/', reports.financial_reports, name='reports-finance'),

] 
