from django.urls import path

from education.views import *

app_name = 'education'

urlpatterns = [

    
    path('test/',test2_view,name='test'),
    path('task/',task_view,name='task'),
    path('online/',onlin_view,name='onlin'),
    path('online_test/',onlin_test_view,name='onlin_test'),
    path('online_text/create/<int:lesson_id>/',onlin_text_view,name='onlin_text'),
    path('faqs/', faqs, name='faqs'),
    path('faqs/<int:pk>/delete/', faq_detail, name='faqs_delete'),
    path('faqs/<int:pk>/update/', faq_update, name='faqs_update'),
    path('online_text/update/<int:pk>/',onlin_text_update_view,name='onlin_text_update'),
    path('online_video/update/<int:pk>/',onlin_video_view,name='onlin_video'),
    path('online_video/delete/<int:pk>/',onlin_hwork_delete_view,name='onlin_video_delete'),
    path('online_video/create/<int:lesson_id>/',onlin_video_create_view,name='onlin_video_create'),
    path('online_hwork/update/<int:pk>/',onlin_hwork_view,name='onlin_hwork'),
    path('online_hwork/delete/<int:pk>/',onlin_hwork_delete_view,name='onlin_delete'),
    path('online_hwork/create/<int:lesson_id>/',onlin_hwork_create_view,name='onlin_hwork_create'),
    path('onlines/<int:id>/',onlins_view,name='onlins'),
    path('onlines/update/<str:type>/<int:pk>/', online_update_view, name='online_update'),
    path('onlines/delete/<str:type>/<int:pk>/', online_delete2_view, name='online_delete2'),
    path('onlines/<str:action>/<str:type>/<int:pk>/', online_activate_view, name='online_activate'),
    path('onlines/<int:id>/delete/',online_delete_view,name='online_delete'),
    path('onlines/<int:id>/contents/', online_course_contents_view, name='online_course_contents'),
    path('onlines/modules/', modules_view, name='modules'),
    path('onlines/modules/<int:pk>/', modules_detail_view, name='module_lessons'),
    path('onlines/<int:pk>/modules/', course_modules_view, name='course_modules'),
    path('onlines/<int:pk>/lessons/', course_lessons_view, name='course_lessons'),
    path('onlines/lessons/create/', create_lesson_view, name='lesson_create'),
    path('onlines/resources/', online_content_resources_view, name='resources'),
    path('onlines/resources/delete/<int:pk>/', online_content_resource_delete_view, name='resources_delete'),    path('lid/',lid_view,name='lid'),
    path('teachers/',teachers_view,name='teachers'),
    path('courses/list/',courses_list_view,name='courses-list'),
    path('course/<int:id>/detail/',course_detail_view,name='course_detail'),
    path('teacher/<int:id>/detail/',teacher_detail_view,name='teacher_detail'),
    path('employe/<int:id>/detail/',employe_detail_view,name='employe_detail'),
    path('group/<int:id>/detail/',group_detail_view,name='group-detail'),
    path('student/<int:id>/detail/',student_detail_view,name='student_detail'),
    path('parents/<int:id>/detail/',parents_detail_view,name='parents_detail'),
    path('debt/<int:id>/groups/',debt_groups_view,name='debt_groups'),
    path('debt/<int:id>/course/',debt_course_view,name='debt_course'),
    path('message/settings/',message_settings_view,name='message-settings'),
    path('teacher/add/',teacher_add_view,name='courseadd'),
    path('groups/list/',groupslist_view,name='groups-list'),
    path('finance/list/',finance_list_view,name='finance-list'),
    path('rooms/list/',roomslist_view,name='rooms-list'),
    path('employees/list/',employees_view,name='employees-list'),
    path('debt/list/',debt_list_view,name='debt-list'),
    path('lid/first/',lid_first_view,name='lid-first'),
    path('lid/sk/',lid_sk_view,name='lid-sk'),
    path('lid/royhati/',lid_royhati_view,name='lid-royhati'),
    path('lid/arxiv/',lid_arxiv_view,name='lid-arxiv'),
    path('lid/ry/',lid_ry_view,name='lid-ry'),
    path('students/list/',students_list_view,name='students-list'),
    path('parents/list/',parents_list_view,name='parents-list'),
    path('expenses/list/',expenses_list_view,name='expenses-list'),

    path('homeworks/', homeworks_view, name='homeworks'),
    path('homeworks/groups/<int:pk>/', group_homeworks_detail_view, name='group-homeworks-detail'),
    path('homeworks/student/<int:pk>/', student_homeworks_in_group, name='student_homeworks'),
    path('homeworks/<str:action>/<int:pk>/', homework_edit_view, name="homework-edit"),
]
