# Generated by Django 4.1.4 on 2023-05-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=160, verbose_name='Xabar matni')),
                ('soums', models.IntegerField(null=True, verbose_name='Sarflangan xarajat')),
                ('timedelta', models.FloatField(null=True, verbose_name='Sarflangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Xabar yaratildi')),
                ('sms_count', models.PositiveIntegerField(default=0, verbose_name='Xabarlar soni')),
                ('dispatch_id', models.IntegerField(blank=True, null=True, verbose_name='Dispatch ID')),
                ('type', models.CharField(max_length=70, null=True, verbose_name='Xabar turi')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefon raqam')),
                ('country', models.CharField(max_length=10, null=True, verbose_name='Davlati')),
                ('status', models.CharField(max_length=20, null=True, verbose_name='Xabar statusi')),
                ('who_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Message',
                'verbose_name_plural': 'SMS Messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SMSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=350, verbose_name='SMS Email')),
                ('password', models.CharField(max_length=350, verbose_name='SMS Password')),
                ('sent_sms', models.IntegerField(default=0, verbose_name='Yuborilgan smslar soni')),
                ('sent_sms_soums', models.PositiveIntegerField(default=0, verbose_name="Sarflangan mablag'")),
                ('free_sms', models.IntegerField(default=100, verbose_name='Yuborilgan smslar soni')),
            ],
            options={
                'verbose_name': 'SMS Account',
                'verbose_name_plural': 'SMS Account',
                'unique_together': {('email', 'password')},
            },
        ),
    ]
