# Generated by Django 4.1.4 on 2023-05-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admintion', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.PositiveIntegerField(null=True, verbose_name="O'quvchining bahosi")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.tests')),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Test Natijalari',
            },
        ),
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='student/homeworks')),
                ('text', models.TextField(blank=True, max_length=5000, verbose_name="O'quvchining javobi")),
                ('ball', models.CharField(blank=True, max_length=10, null=True, verbose_name="Uy vazifasi uchun qo'yilgan baho")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('comment_file', models.FileField(blank=True, null=True, upload_to='student/homeworks/comments')),
                ('comment', models.TextField(blank=True, max_length=5000, verbose_name="O'quvchiga xabar")),
                ('status', models.PositiveSmallIntegerField(choices=[(1, "Ko'rilmagan"), (2, 'Bajarilgan'), (3, 'Baholangan'), (4, 'Rad etilgan')], default=2, verbose_name='Uy vazifasining statusi')),
                ('last_res', models.BooleanField(default=True, verbose_name="Bu o'quvchining oxirgi javobimi?")),
                ('commented', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='education.contents')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.formlead')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.student')),
            ],
            options={
                'verbose_name': 'Uy vazifasi',
                'verbose_name_plural': 'Uy vazifalari',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintion.student')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.testresults')),
            ],
            options={
                'verbose_name': "O'quvchining javobi",
                'verbose_name_plural': "O'quvchilarning javoblari",
                'unique_together': {('student', 'test_result', 'question')},
            },
        ),
    ]
