# Generated by Django 4.1.4 on 2023-05-26 11:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admintion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('content_type', models.SmallIntegerField(choices=[(1, 'Video'), (2, 'Maqola'), (3, 'Test'), (4, 'Vazifa')], default=1, verbose_name='Content Type')),
                ('video', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='Video Material')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Video havola')),
                ('text', models.TextField(blank=True, null=True)),
                ('homework', models.FileField(blank=True, null=True, upload_to='', verbose_name='Uy vazifa uchun topshiriq')),
                ('order', models.IntegerField(default=1, verbose_name="Material o'rni")),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name="O'quvchiga ochilish vaqti")),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilish vaqti')),
                ('required', models.BooleanField(default=False, verbose_name="Dars tugatilmasa keyingi dars ko'rinmasinmi?")),
                ('status', models.BooleanField(default=True, verbose_name='Material tayyormi? ')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.group')),
                ('leads', models.ManyToManyField(blank=True, to='admintion.formlead', verbose_name='Lidlar')),
            ],
            options={
                'verbose_name': 'Dars Materiali',
                'verbose_name_plural': 'Dars Materiallari',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Mavzu sarlavhasi')),
                ('order', models.IntegerField(default=1, verbose_name="Dars o'rni")),
                ('content_type', models.SmallIntegerField(choices=[(1, 'Dars'), (2, 'Test'), (3, 'Uy vazifasi')], default=1, verbose_name='Content Type')),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Material tayyormi?')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.group')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Modul sarlavhasi')),
                ('order', models.IntegerField(default=1, verbose_name="Dars o'rni")),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, verbose_name='Dars tayyormi?')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='admintion.course', verbose_name='Kurs')),
                ('educenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.educenters')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.group')),
            ],
            options={
                'verbose_name': 'Kurs Moduli',
                'verbose_name_plural': 'Kurs Modullari',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_per_student', models.PositiveIntegerField(default=0, verbose_name="1 ta o'quvchi uchun testlar soni")),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name="O'quvchiga ochilish vaqti")),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilish vaqti')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admintion.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.lessons')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.modules')),
            ],
            options={
                'verbose_name': 'Testlar',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Manba')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Manba havolasi')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_resources', to='education.contents', verbose_name='Content')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='education.lessons', verbose_name='Dars')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_resources', to='education.modules', verbose_name='Modul')),
            ],
            options={
                'verbose_name': "Qo'shimcha manbaa",
                'verbose_name_plural': "Qo'shimcha manbaalar",
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Test Savoli')),
                ('ball', models.FloatField(default=0, help_text='Savol necha balli?', verbose_name='Ball')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.tests')),
            ],
            options={
                'verbose_name': 'Test Savoli',
                'verbose_name_plural': 'Test Savollari',
            },
        ),
        migrations.AddField(
            model_name='lessons',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.modules', verbose_name='Modul'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600)),
                ('answer', models.CharField(max_length=1500)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='education.contents')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.AddField(
            model_name='contents',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='education.lessons', verbose_name='Dars'),
        ),
        migrations.AddField(
            model_name='contents',
            name='students',
            field=models.ManyToManyField(blank=True, to='admintion.student', verbose_name='Talabalar'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500, verbose_name='Test javobi')),
                ('is_right', models.BooleanField(verbose_name="To'g'ri javobi?")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='education.questions')),
            ],
            options={
                'verbose_name': 'Test javobi',
                'verbose_name_plural': 'Test javoblari',
            },
        ),
    ]
